### PR TITLE
Revert `89477bd` to allow checking out any git refspec

### PR DESCRIPTION
**Pull request by anoopcs9**
Fixes: #21

### CODE REVIEW

**Review by phlogistonjohn — COMMENTED** [review]
I'm curious as to why you're avoiding the "disconnected head" checkout, and just disable the warning?

This seems a bit more complicated that what we had before you added the `-b` option.Is there some other downside to running `git checkout` the way we were before beyond the warning it prints?

**Comment by anoopcs9** [comment]
> I'm curious as to why you're avoiding the "disconnected head" checkout, and just disable the warning?

Hm..somehow I didn't like it. But that's fine. We can live with the warning(or disable using some git config as you mentioned).

> This seems a bit more complicated that what we had before you added the `-b` option.Is there some other downside to running `git checkout` the way we were before beyond the warning it prints?

But we need to be able to checkout branch, tag and commit hash, right?

**Comment by phlogistonjohn** [comment]
> > I'm curious as to why you're avoiding the "disconnected head" checkout, and just disable the warning?
> 
> Hm..somehow I didn't like it. But that's fine. We can live with the warning(or disable using some git config as you mentioned).
> 

I don't have any issues disabling the warning... and the warning text itself tells you how to disable it.  FWIW I check out commits into disconnected head state fairly often without issue. However, I'm always happy to learn more if there are other issues people run into.

> > This seems a bit more complicated that what we had before you added the `-b` option.Is there some other downside to running `git checkout` the way we were before beyond the warning it prints?
> 
> But we need to be able to checkout branch, tag and commit hash, right?

That's correct. AFAICT, `git checkout {branch/tag/hash}` worked for those cases.  You can't (simply) start making commits on top of the disconnected head in the case of the hash, but this checkout only exists in the container and can be (generally) treated as read-only.

**Comment by anoopcs9** [comment]
> > > This seems a bit more complicated that what we had before you added the `-b` option.Is there some other downside to running `git checkout` the way we were before beyond the warning it prints?
> > 
> > But we need to be able to checkout branch, tag and commit hash, right?
> 
> That's correct. AFAICT, `git checkout {branch/tag/hash}` worked for those cases. You can't (simply) start making commits on top of the disconnected head in the case of the hash, but this checkout only exists in the container and can be (generally) treated as read-only.

Correct.
In that case, revert of 89477bd6e6d810845d6faf21120d439b49a373af would be sufficient here.

**Review by phlogistonjohn — COMMENTED** [review]
I'll approve & merge this as-is if you'd like, but I'll leave this open if you want to disable the warning. If you think its not worth it, please just let me know and we can wrap this up.

**Comment by anoopcs9** [comment]
> I'll approve & merge this as-is if you'd like, but I'll leave this open if you want to disable the warning. If you think its not worth it, please just let me know and we can wrap this up.

Just go ahead with the current revert.

**Review by phlogistonjohn — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
