### PR TITLE
add retry loop to ctdb-must-have-node command

### PR DESCRIPTION
**Pull request by phlogistonjohn**
I was shown a cluster that had failed to communicate with rados during the `ctdb-must-have-node` command, after it had at least correctly read "nothing".
Add a retry loop (with limit) to the command to make it robust against spurious errors.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
@mergifyio rebase

**Review by anoopcs9 — APPROVED** [review]
lgtm.

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Comment by phlogistonjohn** [comment]
@mergifyio refresh

**Comment by phlogistonjohn** [comment]
ok mergify whatever.

**Pull request merged**
